services:
  mysql:
    image: mysql:8.0
    container_name: task-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      interval: 5s
      retries: 10

  backend:
    build:
      context: ./CoveragexTaskBE
      dockerfile: Dockerfile
    container_name: task-backend
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./coveragex-todo
      dockerfile: Dockerfile
    container_name: task-frontend
    ports:
      - "80:80"
    environment:
      API_URL: http://backend:8089/api/tasks
    volumes:
      - ./coveragex-todo/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

networks:
  task-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local