services:
  database:
    image: mysql:8.0
    container_name: task-db
    environment:
      MYSQL_DATABASE: task
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task-network
    command: >
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --skip-log-bin
      --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: 
      context: ./CoveragexTaskBE
      dockerfile: Dockerfile
    container_name: task-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://task-db:3306/task?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8089:8089"
    networks:
      - task-network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build:
      context: ./coveragex-todo
      dockerfile: Dockerfile
    container_name: task-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - task-network

networks:
  task-network:
    driver: bridge

volumes:
  mysql_data: